name: hall_of_fame

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_crashlytics: ^2.8.2
  firebase_dynamic_links: ^4.2.6
  firebase_storage: ^10.2.18
  go_router: ^4.1.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.4
  flutter_screenutil: ^5.5.3+2
  flutter_native_splash: ^2.2.8
  queen_validators: ^1.0.0
  fluttertoast: ^8.0.9
  intl_phone_field: ^3.1.0
  country_pickers: ^2.0.0
  awesome_dialog: ^3.0.0
  lottie: ^1.4.2
  is_first_run: ^1.0.0

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  background_image: assets/images/splahscreen.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/GOTHAM-BLACK.TTF

        - asset: assets/fonts/GOTHAM-BOLD.TTF
        - asset: assets/fonts/Gotham-Book.otf
        - asset: assets/fonts/Gotham-ExtraLight.otf
        - asset: assets/fonts/Gotham-ExtraLightItalic.otf
        - asset: assets/fonts/Gotham-Light.otf
        - asset: assets/fonts/Gotham-LightItalic.otf
        - asset: assets/fonts/Gotham-Medium.otf
          weight: 500
        - asset: assets/fonts/GOTHAM-MEDIUM.TTF
        - asset: assets/fonts/GOTHAM-ULTRA.TTF
    - family: Centaur
      fonts:
        - asset: assets/fonts/CENTAUR.TTF

  assets:
    - assets/images/
    - assets/animation/
